// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB89t7szJDNZfd9c2wgWRtNvOM7tWsQU2o',
    appId: '1:134950611453:android:8f3c6be48bf434d6261194',
    messagingSenderId: '134950611453',
    projectId: 'mock-fuel-delivery-app',
    storageBucket: 'mock-fuel-delivery-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChgICuFdf72JctC9uKS025jv0RORVzlOA',
    appId: '1:134950611453:ios:cd860637aa8d2b54261194',
    messagingSenderId: '134950611453',
    projectId: 'mock-fuel-delivery-app',
    storageBucket: 'mock-fuel-delivery-app.firebasestorage.app',
    iosBundleId: 'com.example.fuelNow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChgICuFdf72JctC9uKS025jv0RORVzlOA',
    appId: '1:134950611453:ios:cd860637aa8d2b54261194',
    messagingSenderId: '134950611453',
    projectId: 'mock-fuel-delivery-app',
    storageBucket: 'mock-fuel-delivery-app.firebasestorage.app',
    iosBundleId: 'com.example.fuelNow',
  );
}
